# Generated by Django 5.0.1 on 2024-01-07 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='iten_no',
            new_name='item_no',
        ),
    ]
