# Generated by Django 5.0.1 on 2024-01-07 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_iten_no_publication_item_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='item_no',
            new_name='item_number',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='name_scp',
            new_name='name_SCP',
        ),
    ]
