# Generated by Django 5.0.1 on 2024-01-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_publication_addendum_alter_publication_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='addendum',
            field=models.TextField(blank=True, null=True),
        ),
    ]
