# Generated by Django 5.0.1 on 2024-05-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_publication_object_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='object_class',
            field=models.CharField(choices=[(0, 'Não Especificado'), (1, 'Seguro'), (2, 'Euclideo'), (3, 'Keter')], default=0, max_length=1),
        ),
    ]
