# Generated by Django 5.0.1 on 2024-05-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_publication_object_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='object_class',
            field=models.CharField(choices=[('NOT_SPECIFIED', 'Não Especificado'), ('SAFE', 'Seguro'), ('EUCLID', 'Euclideo'), ('KETER', 'Keter')], default='NOT_SPECIFIED', max_length=13),
        ),
    ]
